# (c) 2016 DataNexus Inc.  All Rights Reserved
---
# If we're running this command for to build a cluster in an AWS or
# OpenStack cloud, then use the `ec2` or `openstack` command (depending
# on the `cloud` we're deploying into) to gather the dynamic inventory
# information that we need to build our Zookeeper host group (and build it)
- name: Create Zookeeper host group from AWS or OpenStack inventory
  hosts: "{{host_inventory}}"
  gather_facts: no
  tasks:
    # run these commands to add the zookeeper host group for an aws cloud
    - block:
      - name: Run ec2 command to gather inventory information
        local_action: "shell common-utils/inventory/aws/ec2"
        register: di_output
      - set_fact:
          di_output_json: "{{di_output.stdout | from_json}}"
      - set_fact:
          cloud_nodes: "{{di_output_json | json_query('tag_Cloud_' + cloud)}}"
          tenant_nodes: "{{di_output_json | json_query('tag_Tenant_' + tenant)}}"
          project_nodes: "{{di_output_json | json_query('tag_Project_' + project)}}"
          domain_nodes: "{{di_output_json | json_query('tag_Domain_' + domain)}}"
          application_nodes: "{{di_output_json | json_query('tag_Application_' + application)}}"
      - set_fact:
          zookeeper_nodes: "{{cloud_nodes | intersect(tenant_nodes) | intersect(project_nodes) | intersect(domain_nodes) | intersect(application_nodes)}}"
      - add_host:
          name: "{{item}}"
          groups: "zookeeper"
          ansible_ssh_user: "{{ansible_user}}"
          ansible_ssh_private_key_file: "{{private_key_path}}/{{cloud}}-{{di_output_json | json_query('_meta.hostvars.\"' + item + '\".ec2_key_name')}}-private-key.pem"
        with_items: "{{zookeeper_nodes}}"
      when: not (inventory_type is undefined or inventory_type == "static") and cloud == "aws"
      run_once: true
    # or run these commands to add the zookeeper host group for an osp cloud
    - block:
      - name: Run openstack command to gather inventory information
        local_action: "shell common-utils/inventory/osp/openstack"
        register: di_output
      - set_fact:
          di_output_json: "{{di_output.stdout | from_json}}"
      - set_fact:
          cloud_nodes: "{{(di_output_json | json_query('[\"meta-Cloud_' + cloud + '\"]')).0}}"
          tenant_nodes: "{{(di_output_json | json_query('[\"meta-Tenant_' + tenant + '\"]')).0}}"
          project_nodes: "{{(di_output_json | json_query('[\"meta-Project_' + project + '\"]')).0}}"
          domain_nodes: "{{(di_output_json | json_query('[\"meta-Domain_' + domain + '\"]')).0}}"
          application_nodes: "{{(di_output_json | json_query('[\"meta-Application_' + application + '\"]')).0}}"
      - set_fact:
          zookeeper_nodes: "{{cloud_nodes | intersect(tenant_nodes) | intersect(project_nodes) | intersect(domain_nodes) | intersect(application_nodes)}}"
      - add_host:
          name: "{{item}}"
          groups: "zookeeper"
          ansible_ssh_user: "{{ansible_user}}"
          ansible_ssh_private_key_file: "{{private_key_path}}/{{di_output_json | json_query('_meta.hostvars.\"' + item + '\".openstack.key_name')}}.pem"
        with_items: "{{zookeeper_nodes}}"
      when: not (inventory_type is undefined or inventory_type == "static") and cloud == "osp"
      run_once: true

# Otherwise, build our Zookeeper host group from the static inventory
# information that was passed in
- name: Create Zookeeper host group from static host_inventory list
  hosts: "{{host_inventory}}"
  gather_facts: no
  tasks:
    - block:
      - set_fact:
          zookeeper_nodes: "{{host_inventory}}"
      - add_host:
          name: "{{item}}"
          groups: "zookeeper"
        with_items: "{{zookeeper_nodes}}"
      when: inventory_type == "static"
      run_once: true

# Then, deploy Zookeeper to the nodes in the zookeeper host group that was passed in (if there
# is more than one node passed in, those nodes will be configured as a single Zookeeper cluster)
- name: Install/configure servers (zookeeper)
  hosts: zookeeper
  gather_facts: no
  vars_files:
    - vars/zookeeper.yml
  vars:
    - combined_package_list: "{{ (default_packages|default([])) | union(zookeeper_package_list) | union((install_packages_by_tag|default({})).zookeeper|default([])) }}"
  pre_tasks:
    - name: Ensure the network interfaces are up on our Zookeeper node(s)
      service:
        name: network
        state: restarted
      become: true
    - name: Gather facts from the Zookeeper node(s)
      setup:
  roles:
    - role: get-iface-addr
      iface_name: "{{zookeeper_iface}}"
    - role: setup-web-proxy
    - role: add-local-repository
      yum_repository: "{{yum_repo_addr}}"
      when: yum_repo_addr is defined
    - role: install-packages
      package_list: "{{combined_package_list}}"
    - role: dn-zookeeper
      zookeeper_addr: "{{iface_addr}}"
